[phases.setup]
nixPkgs = ['python310', 'python310Packages.pip']

[phases.install]
cmds = ['python -m pip install --upgrade pip', 'pip install -r requirements.txt']

[start]
cmd = 'gunicorn --workers=4 --threads=2 --timeout=120 --bind=0.0.0.0:$PORT web_app.app:app'
