[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn --workers=4 --threads=2 --timeout=120 --bind=0.0.0.0:$PORT web_app.app:app"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
